// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { createServerClient } from '@supabase/ssr'
import { createClient } from '@supabase/supabase-js'
import { NextResponse, type NextRequest } from 'next/server'

const protectedPaths = ["/game","/content"]
const publicPaths = ["/","/login","/auth/callback","/no-access","/start"]
const needAccessAbility = true
const passierscheinId = 'access'
const pageAbilities = {} as Record<string, string>
const APP_NAME = 'japanese-cards'

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl

  // Skip static files
  if (pathname.startsWith('/_next') || pathname.includes('.')) {
    return NextResponse.next()
  }

  // Allow public paths
  if (publicPaths.some(path => pathname === path || pathname.startsWith(path + '/'))) {
    return NextResponse.next()
  }

  // Check if protected
  const isProtected = protectedPaths.some(path =>
    pathname === path || pathname.startsWith(path + '/')
  )

  if (!isProtected) {
    return NextResponse.next()
  }

  // Create Supabase client (Edge Runtime compatible)
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!supabaseUrl || !supabaseKey) {
    console.error('[MIDDLEWARE] Missing env vars')
    return NextResponse.redirect(new URL('/login', request.url))
  }

  const response = NextResponse.next({ request: { headers: request.headers } })

  const supabase = createServerClient(supabaseUrl, supabaseKey, {
    cookies: {
      getAll: () => request.cookies.getAll(),
      setAll: (cookiesToSet) => {
        cookiesToSet.forEach(({ name, value, options }) => {
          request.cookies.set(name, value)
          response.cookies.set(name, value, options)
        })
      },
    },
  })

  // Check session
  const { data: { session } } = await supabase.auth.getSession()

  if (!session) {
    const loginUrl = new URL('/login', request.url)
    loginUrl.searchParams.set('redirect', pathname)
    return NextResponse.redirect(loginUrl)
  }

  // Check abilities if needed (via DB query)
  if ((needAccessAbility || Object.keys(pageAbilities).length > 0) && serviceKey) {
    try {
      const adminClient = createClient(supabaseUrl, serviceKey)
      
      // Fetch user abilities from DB
      const { data: abilities } = await adminClient
        .from('guild_user_abilities')
        .select('ability_id')
        .eq('user_id', session.user.id)
        .eq('app_name', APP_NAME)
      
      const userAbilities = (abilities || []).map((a: any) => a.ability_id as string)

      // Check Passierschein for protected paths
      if (needAccessAbility && !userAbilities.includes(passierscheinId)) {
        const url = new URL('/no-access', request.url)
        url.searchParams.set('id', passierscheinId)
        return NextResponse.redirect(url)
      }

      // Check page-specific abilities
      const pageAbility = pageAbilities[pathname]
      if (pageAbility && !userAbilities.includes(pageAbility)) {
        const url = new URL('/no-access', request.url)
        url.searchParams.set('id', pageAbility)
        return NextResponse.redirect(url)
      }
    } catch (error) {
      console.error('[MIDDLEWARE] Ability check failed:', error)
    }
  }

  return response
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
}
