// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

const APP_NAME = 'japanese-cards'
const APP_DISPLAY_NAME = 'Japanese Cards'
const APP_DESCRIPTION = 'Learn Japanese characters playfully'
const APP_ABILITIES = [
  {
    "id": "access",
    "name": "Passierschein",
    "emoji": "🎫",
    "description": "Zugang zu Japanese Cards",
    "is_passierschein": true
  }
] as const

let lastRegister = 0

async function selfRegister() {
  const now = Date.now()
  if (now - lastRegister < 5 * 60 * 1000) {
    console.log('[HEALTH] Skipping registration (rate limit)')
    return { skipped: true }
  }
  lastRegister = now

  try {
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
    
    console.log('[HEALTH] Starting registration...', {
      hasUrl: !!supabaseUrl,
      hasKey: !!serviceKey,
      keyLength: serviceKey?.length
    })
    
    if (!supabaseUrl || !serviceKey) {
      console.warn('[HEALTH] Missing env vars')
      return { error: 'missing_env' }
    }

    const { createClient } = await import('@supabase/supabase-js')
    const supabase = createClient(supabaseUrl, serviceKey)

    // App registrieren
    const { error: appError } = await supabase
      .from('guild_apps')
      .upsert({
        name: APP_NAME,
        display_name: APP_DISPLAY_NAME,
        version: process.env.NEXT_PUBLIC_APP_VERSION || '0.0.0',
        description: APP_DESCRIPTION,
        last_seen: new Date().toISOString(),
      }, { onConflict: 'name' })
    
    if (appError) {
      console.error('[HEALTH] App registration failed:', appError)
      return { error: appError.message }
    }

    // Fähigkeiten registrieren (mit ID)
    for (const ability of APP_ABILITIES) {
      const { error: abilityError } = await supabase
        .from('guild_abilities')
        .upsert({
          id: ability.id,
          app_name: APP_NAME,
          name: ability.name,
          emoji: ability.emoji || '⚡',
          description: ability.description || '',
          is_passierschein: (ability as any).is_passierschein ?? false,
        }, { onConflict: 'id,app_name' })
      
      if (abilityError) {
        console.error(`[HEALTH] Ability ${ability.id} registration failed:`, abilityError)
      }
    }

    console.log(`[HEALTH] Successfully registered ${APP_NAME} with ${APP_ABILITIES.length} abilities`)
    return { success: true }
  } catch (e: any) {
    console.error('[HEALTH] Self-register exception:', e)
    return { error: e.message }
  }
}

export async function GET() {
  const registerResult = await selfRegister()

  return NextResponse.json({
    status: 'ok',
    timestamp: new Date().toISOString(),
    app: APP_NAME,
    version: process.env.NEXT_PUBLIC_APP_VERSION || '0.0.0',
    registration: registerResult,
  })
}
