// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { createHealthHandler } from '@michalsy/aiko-webapp-core/server'

export const dynamic = 'force-dynamic'

export const GET = createHealthHandler({
  appName: 'japanese-cards',
  displayName: 'Japanese Cards',
  description: 'Learn Japanese characters playfully',
  abilities: [
  {
    "id": "access",
    "name": "Passierschein",
    "emoji": "🎫",
    "description": "Zugang zu Japanese Cards",
    "is_passierschein": true
  }
],
})
