// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { createMeAccessHandler } from '@michalsy/aiko-webapp-core/server'

export const dynamic = 'force-dynamic'

export const GET = createMeAccessHandler({
  appName: 'japanese-cards',
  passierscheinId: 'access',
  abilities: [
  {
    "id": "access",
    "name": "Passierschein",
    "emoji": "🎫",
    "description": "Zugang zu Japanese Cards",
    "is_passierschein": true
  }
],
})
