// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { createDevLoginHandler } from '@michalsy/aiko-webapp-core/server'

export const dynamic = 'force-dynamic'

export const POST = createDevLoginHandler({
  audience: "japanese-cards",
  appName: "japanese-cards",
  abilityId: "access",
  defaultRedirect: "/",
})
