// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

'use client'

import { useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@michalsy/aiko-webapp-core'
import { useAbilities } from '@/contexts/AbilitiesContext'

// Page config from aikoapp.json
const PAGES = [
  {
    "path": "/",
    "ability": "access"
  }
] as const
const PASSIERSCHEIN = 'access'

export default function StartPage() {
  const router = useRouter()
  const { user, loading: authLoading } = useAuth()
  const { abilities, loading: abilitiesLoading } = useAbilities()

  useEffect(() => {
    if (authLoading || abilitiesLoading) return

    if (!user) {
      router.replace('/login')
      return
    }

    // Check for Passierschein
    if (!abilities.includes(PASSIERSCHEIN)) {
      router.replace('/no-access')
      return
    }

    // Find first accessible page
    const accessiblePage = PAGES.find(page => 
      abilities.includes(page.ability)
    )

    if (accessiblePage) {
      router.replace(accessiblePage.path)
    } else {
      // Fallback - should not happen if user has Passierschein
      router.replace('/no-access')
    }
  }, [authLoading, abilitiesLoading, user, abilities, router])

  return (
    <div style={{
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      height: '100vh',
      background: 'radial-gradient(circle at 15% 10%, rgba(236,72,153,0.4) 0%, transparent 50%), radial-gradient(circle at 85% 95%, rgba(236,72,153,0.3) 0%, transparent 50%), linear-gradient(135deg, #1a1a3e 0%, #2d1b4e 25%, #0f172a 50%, #0d1e3f 100%)',
      fontSize: '15px', color: 'rgba(255,255,255,0.5)', fontFamily: "'Outfit', system-ui, sans-serif",
    }}>
      Prüfe Passierschein...
    </div>
  )
}
