// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

'use client'

import { useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@michalsy/aiko-webapp-core'
import { useAbilities } from '@/contexts/AbilitiesContext'

// Page config from aikoapp.json
const PAGES = [
  {
    "path": "/game",
    "ability": "access"
  },
  {
    "path": "/content",
    "ability": "access"
  }
] as const
const PASSIERSCHEIN = 'access'

export default function StartPage() {
  const router = useRouter()
  const { user, loading: authLoading } = useAuth()
  const { abilities, loading: abilitiesLoading } = useAbilities()

  useEffect(() => {
    if (authLoading || abilitiesLoading) return

    if (!user) {
      router.replace('/login')
      return
    }

    // Check for Passierschein
    if (!abilities.includes(PASSIERSCHEIN)) {
      router.replace('/no-access')
      return
    }

    // Find first accessible page
    const accessiblePage = PAGES.find(page => 
      abilities.includes(page.ability)
    )

    if (accessiblePage) {
      router.replace(accessiblePage.path)
    } else {
      // Fallback - should not happen if user has Passierschein
      router.replace('/no-access')
    }
  }, [authLoading, abilitiesLoading, user, abilities, router])

  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      height: '100vh',
      background: '#0a0a0a',
      fontSize: '1.2rem',
      color: '#666'
    }}>
      Prüfe Passierschein...
    </div>
  )
}
