// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import LoginForm from '@michalsy/aiko-webapp-core/login'

export const dynamic = 'force-static'

export default function LoginPage() {
  return (
    <LoginForm
      title="Irasshaimase! 🌸"
      subtitle="Learn Japanese Characters"
      buttonText="Sign in with Google"
      redirectUrl="/start"
      
      
      
    />
  )
}
