// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

export const PAGES = [
  {
    "path": "/",
    "label": "Home",
    "icon": "🏠"
  },
  {
    "path": "/content",
    "label": "Content",
    "icon": "📚"
  },
  {
    "path": "/game",
    "label": "Game",
    "icon": "🎮"
  }
] as const

export const SIDEBAR_PAGES = [
  {
    "path": "/",
    "label": "Home",
    "icon": "🏠"
  },
  {
    "path": "/content",
    "label": "Content",
    "icon": "📚"
  },
  {
    "path": "/game",
    "label": "Game",
    "icon": "🎮"
  }
] as const

export const TOPBAR_PAGES = [] as const

export type PageConfig = typeof PAGES[number]
