// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { AbilitiesProvider } from '@/contexts/AbilitiesContext'
import { AuthProvider, LanguageProvider } from '@michalsy/aiko-webapp-core'
import '@michalsy/aiko-webapp-core/core.css'
import './globals.css'

export const metadata = {
  title: 'Japanese Cards',
  description: 'Learn Japanese characters playfully',
  themeColor: '#0f172a',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de">
      <body className="antialiased">
        <AuthProvider>
          <LanguageProvider>
            <AbilitiesProvider>
              {children}
            </AbilitiesProvider>
          </LanguageProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
