// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

'use client'

import { useSearchParams } from 'next/navigation'
import { Suspense } from 'react'

const ABILITIES: Record<string, { name: string; emoji: string; description: string }> = {
  "access": {
    "name": "Passierschein",
    "emoji": "🎫",
    "description": "Zugang zu Japanese Cards"
  }
}

function NoAccessContent() {
  const searchParams = useSearchParams()
  const abilityId = searchParams.get('id') || 'access'
  const ability = ABILITIES[abilityId] || { name: 'Unbekannt', emoji: '🚫', description: '' }
  
  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundImage: 'url("/bg.jpg")',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      fontFamily: 'system-ui, sans-serif'
    }}>
      <div style={{
        textAlign: 'center',
        padding: '3rem',
        maxWidth: '480px',
        background: 'rgba(20, 20, 30, 0.9)',
        borderRadius: '1.5rem',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
        border: '1px solid rgba(0, 255, 136, 0.2)',
        backdropFilter: 'blur(10px)'
      }}>
        <div style={{ fontSize: '4rem', marginBottom: '1rem' }}>🚫{ability.emoji}</div>
        <h1 style={{
          margin: '0 0 0.5rem',
          fontSize: '1.5rem',
          color: '#00ff88',
          textShadow: '0 0 20px rgba(0, 255, 136, 0.5)'
        }}>
          Fehlende Berechtigung!
        </h1>
        <p style={{ color: '#888', marginBottom: '2rem', lineHeight: 1.6 }}>
          Du benötigst <strong style={{ color: '#00ff88' }}>{ability.emoji} {ability.name}</strong> für diese Seite.<br />
          Bitte beim <strong>Gildenmeister</strong> anfragen.
        </p>
        <div style={{
          background: 'rgba(0, 255, 136, 0.1)',
          border: '1px solid rgba(0, 255, 136, 0.3)',
          borderRadius: '1rem',
          padding: '1rem',
          marginBottom: '1.5rem',
          fontSize: '0.85rem',
          color: '#aaa'
        }}>
          {ability.emoji} <strong style={{ color: '#00ff88' }}>{ability.name}</strong> {ability.description ? '- ' + ability.description : ''}
        </div>
        <a href="/start" style={{
          display: 'inline-block',
          padding: '0.75rem 1.5rem',
          background: '#00ff88',
          color: '#0a0a0a',
          borderRadius: '0.75rem',
          textDecoration: 'none',
          fontWeight: 600,
          fontSize: '0.9rem'
        }}>
          ← Zurück zur App
        </a>
      </div>
    </div>
  )
}

export default function NoAccessPage() {
  return (
    <Suspense fallback={<div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888' }}>Laden...</div>}>
      <NoAccessContent />
    </Suspense>
  )
}
