// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { handleAuthCallback } from '@michalsy/aiko-webapp-core/auth/callback'

export const GET = (req: Request) =>
  handleAuthCallback(req, {
    successRedirect: '/start',
    errorRedirect: '/login?error=auth_failed',
  })
