// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

export const PAGES = [
  {
    "path": "/content/hiragana",
    "label": "Hiragana",
    "icon": "あ"
  },
  {
    "path": "/content/words",
    "label": "Wörter",
    "icon": "📚"
  }
] as const

export const SIDEBAR_PAGES = [
  {
    "path": "/content/hiragana",
    "label": "Hiragana",
    "icon": "あ"
  },
  {
    "path": "/content/words",
    "label": "Wörter",
    "icon": "📚"
  }
] as const

export const TOPBAR_PAGES = [] as const

export type PageConfig = typeof PAGES[number]
