// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

'use client'

import { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react'
import { useAuth } from '@michalsy/aiko-webapp-core'

interface AbilitiesContextType {
  abilities: string[]
  hasAbility: (id: string) => boolean
  hasPassierschein: boolean
  loading: boolean
}

const AbilitiesContext = createContext<AbilitiesContextType>({
  abilities: [],
  hasAbility: () => false,
  hasPassierschein: false,
  loading: true,
})

export function AbilitiesProvider({ children }: { children: ReactNode }) {
  const { user, loading: authLoading } = useAuth()
  const [abilities, setAbilities] = useState<string[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (authLoading) return

    if (!user) {
      setAbilities([])
      setLoading(false)
      return
    }

    setLoading(true)
    fetch('/api/me/access')
      .then(r => r.json())
      .then(data => {
        setAbilities(data.abilities || [])
        setLoading(false)
      })
      .catch(() => {
        setAbilities([])
        setLoading(false)
      })
  }, [user?.id, authLoading])

  const hasAbility = useCallback((id: string) => abilities.includes(id), [abilities])
  const hasPassierschein = abilities.includes('access')

  return (
    <AbilitiesContext.Provider value={{ abilities, hasAbility, hasPassierschein, loading }}>
      {children}
    </AbilitiesContext.Provider>
  )
}

export function useAbilities() {
  return useContext(AbilitiesContext)
}
